### ISSUE TITLE
提供一些也许可供参考的文档

### ISSUE THREAD

**Issue by criwits** [Coiggahou2002/YourMissingComputerGuide#1]
同学好！

很高兴能看到有人能以原创文档的形式，为更多同学填平学习计算机专业之路上「常识」和「专业教育」之间的鸿沟。其实我在今年上半年也有写过一套近 6 万字的文档《你缺失的那门计算机课》，只不过是面向「电脑小白」群体，教大家一些最基本的「计算机常识」的。也许这套拙作能为你的创作带来参考。

这套文档的链接是 <https://missing.criwits.top>，文字仓库在 <https://github.com/criwits/missing-web>，LaTeX 排版的 PDF 在 <https://github.com/criwits/missing-pdf/>。不过这些文字已经停更许久，希望它们还能用得上。

顺颂秋祺。

**Comment by Coiggahou2002** [comment]
thanks for sharing :)
welcome to join as a collaborator&nbsp;if you like

---原始邮件---
发件人: "Hans ***@***.***&gt;
发送时间: 2022年9月30日(周五) 上午10:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Coiggahou2002/YourMissingComputerGuide] 提供一些也许可供参考的文档 (Issue #1)




 
同学好！
 
很高兴能看到有人能以原创文档的形式，为更多同学填平学习计算机专业之路上「常识」和「专业教育」之间的鸿沟。其实我在今年上半年也有写过一套近 6 万字的文档《你缺失的那门计算机课》，只不过是面向「电脑小白」群体，教大家一些最基本的「计算机常识」的。也许这套拙作能为你的创作带来参考。
 
这套文档的链接是 https://missing.criwits.top，文字仓库在 https://github.com/criwits/missing-web，LaTeX 排版的 PDF 在 https://github.com/criwits/missing-pdf/。不过这些文字已经停更许久，希望它们还能用得上。
 
顺颂秋祺。
